version: '3.5'

services:
  senja-api:
    container_name: senja-api
    image: senja-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_URL: jdbc:postgresql://senjaapi:5432/senjaapi
  senjaapi:
    container_name: "senjaapi"
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: senjaapi